# Generated by Django 5.0.7 on 2024-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09181112233', max_length=11),
            preserve_default=False,
        ),
    ]
