# Generated by Django 5.0.7 on 2024-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
