# Generated by Django 5.0.7 on 2024-10-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_usersubscription_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=10),
        ),
    ]
