# Generated by Django 5.0.7 on 2024-10-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='zarinapl_data',
            new_name='zarinpal_data',
        ),
    ]
