# Generated by Django 5.0.7 on 2024-08-04 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.IntegerField(choices=[('5', 'Product Rate Five Star'), ('4', 'Product Rate Four Star'), ('3', 'Product Rate Three Star'), ('2', 'Product Rate Two Star'), ('1', 'Product Rate One Star'), ("[(5, 'EXCELLENT'), (4, 'GOOD'), (3, 'NOT BAD'), (2, 'BAD'), (1, 'VERY BAD')]", 'Product Rate Choices')]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('a', 'approved'), ('na', 'not-approved'), ('w', 'waiting')], max_length=2)),
                ('rate', models.IntegerField(choices=[('5', 'Product Rate Five Star'), ('4', 'Product Rate Four Star'), ('3', 'Product Rate Three Star'), ('2', 'Product Rate Two Star'), ('1', 'Product Rate One Star'), ("[(5, 'EXCELLENT'), (4, 'GOOD'), (3, 'NOT BAD'), (2, 'BAD'), (1, 'VERY BAD')]", 'Product Rate Choices')])),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
