# Generated by Django 5.0.7 on 2024-08-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_rate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.CharField(choices=[("(5, 'EXCELLENT')", 'Product Rate Five Star'), ("(4, 'GOOD')", 'Product Rate Four Star'), ("(3, 'NOT BAD')", 'Product Rate Three Star'), ("(2, 'BAD')", 'Product Rate Two Star'), ("(1, 'VERY BAD')", 'Product Rate One Star')], max_length=16),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('na', 'not-approved'), ('w', 'waiting')], default='waiting', max_length=2),
        ),
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.CharField(choices=[("(5, 'EXCELLENT')", 'Product Rate Five Star'), ("(4, 'GOOD')", 'Product Rate Four Star'), ("(3, 'NOT BAD')", 'Product Rate Three Star'), ("(2, 'BAD')", 'Product Rate Two Star'), ("(1, 'VERY BAD')", 'Product Rate One Star')], max_length=16),
        ),
    ]
