# Generated by Django 5.0.7 on 2024-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_comment_rate_alter_comment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.CharField(choices=[('5', 'EXCELLENT'), ('4', 'GOOD'), ('3', 'NOT BAD'), ('2', 'BAD'), ('1', 'VERY BAD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.CharField(choices=[('5', 'EXCELLENT'), ('4', 'GOOD'), ('3', 'NOT BAD'), ('2', 'BAD'), ('1', 'VERY BAD')], max_length=16),
        ),
    ]
