# Generated by Django 5.0.7 on 2024-08-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_comment_rate_alter_content_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('na', 'not-approved'), ('w', 'waiting')], default='w', max_length=2),
        ),
    ]
