# Generated by Django 5.0.7 on 2024-10-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=255, upload_to='videos'),
        ),
    ]
