# Generated by Django 5.0.7 on 2024-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_video_content_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
