# Generated by Django 5.0.7 on 2024-11-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_genre_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('title', 'tmdb_id')},
        ),
    ]
