# Generated by Django 5.0.7 on 2024-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_genre_tmdb_id_alter_genre_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.CharField(blank=True, choices=[('5', 'EXCELLENT'), ('4', 'GOOD'), ('3', 'NOT BAD'), ('2', 'BAD'), ('1', 'VERY BAD')], max_length=16, null=True),
        ),
    ]
