# Generated by Django 5.0.7 on 2024-08-25 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_comment_status'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.PositiveIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='content.content')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order.order')),
            ],
            options={
                'unique_together': {('order', 'content')},
            },
        ),
    ]
